#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          fint-idp:
#            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer=fint-api
#        registration:
#          fint:
#            provider: fint-idp




spring:
  security:
    oauth2:
      client:

        registration:
          fint:
            scope:
              - openid
              - end-user-profile
            authorization-grant-type: authorization_code
            redirect-uri: http://whoami.example.com/login/oauth2/code/fint

        provider:
          fint:
            issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
            authorization-uri: https://idp.felleskomponent.no/nidp/oauth/nam/authz
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer=fint-api
            user-info-uri: https://idp.felleskomponent.no/nidp/oauth/nam/userinfo
            #user-name-attribute: user_name
