fint:
  sso:
    logout-message: Du er logget ut.
    idpHost: idp.felleskomponent.no
spring:
  thymeleaf:
    reactive:
      max-chunk-size: 8192
  webflux:
    static-path-pattern: /_oauth/assets/**
logging:
  level:
    root: error
    no.fintlabs: debug

TZ: Europe/Oslo