fint:
  sso:
    logout-message: Du er logget ut.
    idpHost: idp.felleskomponent.no
spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    reactive:
      max-chunk-size: 8192
logging:
  level:
    no:
      fintlabs: debug
TZ: Europe/Oslo
