fint:
  sso:
    logout-message: Du er logget ut.
    # This should be set to the refresh token timeout value of the IDP
    session-max-age-in-minutes: 1440
spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    reactive:
      max-chunk-size: 8192
logging:
  level:
    no:
      fintlabs: debug
TZ: Europe/Oslo
