fint:
  sso:
    logout-message: Du er logget ut.

spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    reactive:
      max-chunk-size: 8192
logging:
  level:
    no:
      fintlabs: debug

