apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - middleware.yaml
  - oauthclient.yaml
  - ingress-route.yaml
  - deployment.yaml
namePrefix: flais-
namespace: flais-auth-forward-simple-test
commonLabels:
  app.kubernetes.io/name: flais-auth-forward
  app.kubernetes.io/instance: flais-auth-forward-simple-test
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/managed-by: "manually"
  app.kubernetes.io/component: traefik-forward-auth-service
  app.kubernetes.io/part-of: FINTLabs-Application-Infrastructure-Services
  fintlabs.no/team: flais




