#
# Example Application Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: ghcr.io/fintlabs/flais-auth-forward-simple-test-service:sha-61bbf46
        ports:
        - containerPort: 8080
          protocol: TCP
---
#
# Service
#
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: whoami

---
#
# IngressRoute
#
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  entryPoints:
    - web
  routes:
  #- match: Host(`frode-test.fintlabs.no`) # && PathPrefix(`/`)
  - match: Host(`whoami.example.com`) # && PathPrefix(`/`)
    kind: Rule
    services:
      - name: whoami
        port: 8080
#    middlewares:
#      - name: traefik-forward-auth
