apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: ghcr.io/fintlabs/flais-auth-forward-service:sha-a94bef8
        name: traefik-forward-auth
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: fint.sso.client-id
          value: 9a69bf9b-c8a7-4b31-be0d-d848e789edfe
        - name: fint.sso.client-secret
          value: Hz4CmAzQpLHySDfbvahvJtSHZpGINxmcijyITg-W0r4z6DVq88ZChtxn2ljZe6iJMQJmHmeenqF-NUMwRq3MhA
        - name: logging.level.no.fintlabs
          value: debug

---
#
# Auth Service
#
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  type: ClusterIP
  selector:
    app: traefik-forward-auth
  ports:
  - name: auth-http
    port: 8080
    targetPort: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`frode-test.fintlabs.no`) && PathPrefix(`/_oauth`)
    kind: Rule
    services:
      - name: traefik-forward-auth
        port: 8080


---
#
# Auth Middleware
#
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
spec:
  forwardAuth:
    #address: https://frode-test.fintlabs.no/_oauth
    address: http://traefik-forward-auth:8080/_oauth
    authResponseHeaders:
      - Authorization
    trustForwardHeader: true

---

