
# Traefik Forward Auth Deployment

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: traefik-forward-auth
#   labels:
#     app: traefik-forward-auth
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: traefik-forward-auth
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: traefik-forward-auth
#     spec:
#       terminationGracePeriodSeconds: 60
#       containers:
#       - image: thomseddon/traefik-forward-auth:2
#         name: traefik-forward-auth
#         ports:
#         - containerPort: 4181
#           protocol: TCP
#         env:
#         # - name: DOMAIN
#         #   value: "example.com"
#         # INSECURE_COOKIE is required unless using https entrypoint
#         - name: INSECURE_COOKIE
#           value: "true"
#         - name: DEFAULT_PROVIDER
#           value: "oidc"
#         - name: PROVIDERS_OIDC_ISSUER_URL
#           value: "https://idp.felleskomponent.no/nidp/oauth/nam"
#         - name: PROVIDERS_OIDC_CLIENT_ID
#           value: "9a69bf9b-c8a7-4b31-be0d-d848e789edfe"
#         - name: PROVIDERS_OIDC_CLIENT_SECRET
#           value: "Hz4CmAzQpLHySDfbvahvJtSHZpGINxmcijyITg-W0r4z6DVq88ZChtxn2ljZe6iJMQJmHmeenqF-NUMwRq3MhA"
#         - name: SECRET
#           value: "qwerty12"
#         - name: LOG_LEVEL
#           value: debug

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: ghcr.io/fintlabs/flais-auth-forward-service:sha-98759fa
        name: traefik-forward-auth
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: fint.sso.client-id
          value: 9a69bf9b-c8a7-4b31-be0d-d848e789edfe
        - name: fint.sso.client-secret
          value: Hz4CmAzQpLHySDfbvahvJtSHZpGINxmcijyITg-W0r4z6DVq88ZChtxn2ljZe6iJMQJmHmeenqF-NUMwRq3MhA
        - name: logging.level.no.fintlabs
          value: debug

---
#
# Auth Service
#
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  type: ClusterIP
  selector:
    app: traefik-forward-auth
  ports:
  - name: auth-http
    port: 8080
    targetPort: 8080

---
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: traefik-forward-auth
#  labels:
#    app: traefik-forward-auth
#spec:
#  entryPoints:
#    - web
#  routes:
#  - match: Host(`frode-test.fintlabs.no`) && (PathPrefix(`/login`) || PathPrefix(`/logout`) || PathPrefix(`/auth`) || PathPrefix(`/oauth2`))
#  #- match: Host(`frode-test.fintlabs.no`) && PathPrefix(`/auth`)
#    kind: Rule
#    services:
#      - name: traefik-forward-auth
#        port: 8080


---
#
# Auth Middleware
#
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: http://traefik-forward-auth:8080/auth
    authResponseHeaders:
      - Authorization
    #trustForwardHeader: true

---
#
# Secrets
#
# Kubernetes requires secret values to be converted to base64 when defined
# explicitly like this. (use `echo -n 'secret-value' | base64`)
#
# These are here for completeness, in reality you may define these elsewhere,
# for example using kustomize (shown in advanced examples)
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: traefik-forward-auth-secrets
#   labels:
#     app: traefik-forward-auth
# type: Opaque
# data:
#   traefik-forward-auth-google-client-id: base64-client-id
#   traefik-forward-auth-google-client-secret: base64-client-secret
#   traefik-forward-auth-secret: base64-something-random
