apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patchesStrategicMerge:
  - middleware.yaml
  - oauthclient.yaml
  - ingress-route.yaml
  - deployment.yaml
namePrefix: fint-flyt-
namespace: viken-test
commonLabels:
  app.kubernetes.io/name: flais-auth-forward
  app.kubernetes.io/instance: fint-flyt-auth-forward
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/managed-by: "manually"
  app.kubernetes.io/component: traefik-forward-auth-service
  app.kubernetes.io/part-of: fint-flyt-viken-test
  fintlabs.no/team: flyt




